#pragma once
#include "driver/gpio.h"

#define PIN_BUTTON_LEFT   GPIO_NUM_01
#define PIN_BUTTON_RIGHT  GPIO_NUM_02
#define PIN_BUTTON_SELECT GPIO_NUM_41
#define PIN_BUTTON_POWER  GPIO_NUM_42

#define PIN_DISPLAY_SCLK  GPIO_NUM_04
#define PIN_DISPLAY_MOSI  GPIO_NUM_05
#define PIN_DISPLAY_CS    GPIO_NUM_06
#define PIN_DISPLAY_RESET GPIO_NUM_07
#define PIN_DISPLAY_DC    GPIO_NUM_15
#define PIN_DISPLAY_BL    GPIO_NUM_16