#pragma once
#include "driver/gpio.h"

#define PIN_BUTTON_LEFT   GPIO_NUM_1
#define PIN_BUTTON_RIGHT  GPIO_NUM_2
#define PIN_BUTTON_POWER  GPIO_NUM_42
#define PIN_BUTTON_SELECT GPIO_NUM_41

#define PIN_DISPLAY_MOSI  GPIO_NUM_5
#define PIN_DISPLAY_SCLK  GPIO_NUM_4
#define PIN_DISPLAY_CS    GPIO_NUM_6
#define PIN_DISPLAY_DC    GPIO_NUM_15
#define PIN_DISPLAY_RESET GPIO_NUM_7
#define PIN_DISPLAY_BL    GPIO_NUM_16