name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        idf_target: ["esp32s3"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Build with ESP-IDF
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.5
          target: ${{ matrix.idf_target }}
          path: '.'
